<?php
/**
 * @package EasyWPTranslator
 */
namespace EasyWPTranslator\Settings\Controllers;
if ( ! defined( 'ABSPATH' ) ) {
	exit; // Don't access directly
}

/**
 * The list of predefined languages
 * For WordPress locales.
 * For W3C locales, see http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
 * See also #33511
 * Facebook locales used to be available at https://www.facebook.com/translations/FacebookLocales.xml
 *
 * For each language:
 * [code]     => ISO 639-1 language code
 * [locale]   => WordPress locale
 * [name]     => name
 * [dir]      => text direction
 * [flag]     => flag code
 * [w3c]      => W3C locale
 * [facebook] => Facebook locale
 *
 * Facebook locales without equivalent WordPress locale:
 * 'ay_BO' (Aymara)
 * 'bp_IN' (Bhojpuri)
 * 'ck_US' (Cherokee)
 * 'en_IN' (English India)
 * 'gx_GR' (Classical Greek)
 * 'ig_NG' (Igbo)
 * 'ik_US' (Inupiak)
 * 'iu_CA' (Inuktitut)
 * 'ja_KS' (Japanese Kansai)
 * 'ks_IN' (Cachemiri)
 * 'lg_UG' (Ganda)
 * 'nd_ZW' (Ndebele)
 * 'nr_ZA' (Southern Ndebele)
 * 'ns_ZA' (Northern Sotho)
 * 'ny_MW' (Chewa)
 * 'qc_GT' (Quiché)
 * 'qu_PE' (Quechua)
 * 'se_NO' (Northern Sami)
 * 'ss_SZ' (Swazi)
 * 'st_ZA' (Southern Sotho)
 * 'tl_ST' (Klingon)
 * 'tn_BW' (Tswana)
 * 'ts_ZA' (Tsonga)
 * 've_ZA' (Venda)
 * 'wo_SN' (Wolof)
 * 'yi_DE' (Yiddish)
 * 'zu_ZA' (Zulu)
 * 'zz_TR' (Zazaki)
 */
return array(
	'af' => array(
		'code'     => 'af',
		'locale'   => 'af',
		'name'     => 'Afrikaans',
		'label'    => 'Afrikaans',
		'dir'      => 'ltr',
		'flag'     => 'za',
		'facebook' => 'af_ZA',
	),
	'ak' => array(
		'facebook' => 'ak_GH',
		'label'    => 'Akan',
	),
	'am' => array(
		'code'     => 'am',
		'locale'   => 'am',
		'name'     => 'አማርኛ',
		'label'    => 'Amharic',
		'dir'      => 'ltr',
		'flag'     => 'et',
		'facebook' => 'am_ET',
	),
	'ar' => array(
		'code'     => 'ar',
		'locale'   => 'ar',
		'name'     => 'العربية',
		'label'    => 'Arabic',
		'dir'      => 'rtl',
		'flag'     => 'arab',
		'facebook' => 'ar_AR',
		'deepl'    => 'AR',
	),
	'arg' => array(
		'code'     => 'an',
		'locale'   => 'arg',
		'name'     => 'Aragonés',
		'label'    => 'Aragonese',
		'dir'      => 'ltr',
		'flag'     => 'es',
	),
	'arq' => array(
		'facebook' => 'ar_AR',
		'label'    => 'Algerian Arabic',
	),
	'ary' => array(
		'code'     => 'ar',
		'locale'   => 'ary',
		'name'     => 'العربية المغربية',
		'label'    => 'Moroccan Arabic',
		'dir'      => 'rtl',
		'flag'     => 'ma',
		'facebook' => 'ar_AR',
		'deepl'    => 'AR',
	),
	'as' => array(
		'code'     => 'as',
		'locale'   => 'as',
		'name'     => 'অসমীয়া',
		'label'    => 'Assamese',
		'dir'      => 'ltr',
		'flag'     => 'in',
		'facebook' => 'as_IN',
	),
	'az' => array(
		'code'     => 'az',
		'locale'   => 'az',
		'name'     => 'Azərbaycan',
		'label'    => 'Azerbaijani',
		'dir'      => 'ltr',
		'flag'     => 'az',
		'facebook' => 'az_AZ',
	),
	'azb' => array(
		'code'     => 'azb',
		'locale'   => 'azb',
		'name'     => 'گؤنئی آذربایجان',
		'label'    => 'South Azerbaijani',
		'dir'      => 'rtl',
		'flag'     => 'az',
	),
	'bel' => array(
		'code'     => 'be',
		'locale'   => 'bel',
		'name'     => 'Беларуская мова',
		'label'    => 'Belarusian',
		'dir'      => 'ltr',
		'flag'     => 'by',
		'w3c'      => 'be',
		'facebook' => 'be_BY',
	),
	'bg_BG' => array(
		'code'     => 'bg',
		'locale'   => 'bg_BG',
		'name'     => 'български',
		'label'    => 'Bulgarian',
		'dir'      => 'ltr',
		'flag'     => 'bg',
		'facebook' => 'bg_BG',
		'deepl'    => 'BG',
	),
	'bn_BD' => array(
		'code'     => 'bn',
		'locale'   => 'bn_BD',
		'name'     => 'বাংলা',
		'label'    => 'Bengali',
		'dir'      => 'ltr',
		'flag'     => 'bd',
		'facebook' => 'bn_IN',
	),
	'bo' => array(
		'code'     => 'bo',
		'locale'   => 'bo',
		'name'     => 'བོད་ཡིག',
		'label'    => 'Tibetan',
		'dir'      => 'ltr',
		'flag'     => 'tibet',
	),
	'bre' => array(
		'w3c'      => 'br',
		'facebook' => 'br_FR',
		'label'    => 'Breton',
	),
	'bs_BA' => array(
		'code'     => 'bs',
		'locale'   => 'bs_BA',
		'name'     => 'Bosanski',
		'label'    => 'Bosnian',
		'dir'      => 'ltr',
		'flag'     => 'ba',
		'facebook' => 'bs_BA',
	),
	'ca' => array(
		'code'     => 'ca',
		'locale'   => 'ca',
		'name'     => 'Català',
		'label'    => 'Catalan',
		'dir'      => 'ltr',
		'flag'     => 'catalonia',
		'facebook' => 'ca_ES',
	),
	'ceb' => array(
		'code'     => 'ceb',
		'locale'   => 'ceb',
		'name'     => 'Cebuano',
		'label'    => 'Cebuano',
		'dir'      => 'ltr',
		'flag'     => 'ph',
		'facebook' => 'cx_PH',
	),
	'ckb' => array(
		'code'     => 'ku',
		'locale'   => 'ckb',
		'name'     => 'کوردی',
		'label'    => 'Kurdish (Sorani)',
		'dir'      => 'rtl',
		'flag'     => 'kurdistan',
		'facebook' => 'cb_IQ',
	),
	'co' => array(
		'facebook' => 'co_FR',
		'label'    => 'Corsican',
	),
	'cs_CZ' => array(
		'code'     => 'cs',
		'locale'   => 'cs_CZ',
		'name'     => 'Čeština',
		'label'    => 'Czech',
		'dir'      => 'ltr',
		'flag'     => 'cz',
		'facebook' => 'cs_CZ',
		'deepl'    => 'CS',
	),
	'cy' => array(
		'code'     => 'cy',
		'locale'   => 'cy',
		'name'     => 'Cymraeg',
		'label'    => 'Welsh',
		'dir'      => 'ltr',
		'flag'     => 'wales',
		'facebook' => 'cy_GB',
	),
	'da_DK' => array(
		'code'     => 'da',
		'locale'   => 'da_DK',
		'name'     => 'Dansk',
		'label'    => 'Danish',
		'dir'      => 'ltr',
		'flag'     => 'dk',
		'facebook' => 'da_DK',
		'deepl'    => 'DA',
	),
	'de_AT' => array(
		'code'     => 'de',
		'locale'   => 'de_AT',
		'name'     => 'Deutsch',
		'label'    => 'German',
		'dir'      => 'ltr',
		'flag'     => 'at',
		'facebook' => 'de_DE',
		'deepl'    => 'DE',
	),
	'de_CH' => array(
		'code'     => 'de',
		'locale'   => 'de_CH',
		'name'     => 'Deutsch',
		'label'    => 'German',
		'dir'      => 'ltr',
		'flag'     => 'ch',
		'facebook' => 'de_DE',
		'deepl'    => 'DE',
	),
	'de_CH_informal' => array(
		'code'     => 'de',
		'locale'   => 'de_CH_informal',
		'name'     => 'Deutsch',
		'label'    => 'German',
		'dir'      => 'ltr',
		'flag'     => 'ch',
		'w3c'      => 'de-CH',
		'facebook' => 'de_DE',
		'deepl'    => 'DE',
	),
	'de_DE' => array(
		'code'     => 'de',
		'locale'   => 'de_DE',
		'name'     => 'Deutsch',
		'label'    => 'German',
		'dir'      => 'ltr',
		'flag'     => 'de',
		'facebook' => 'de_DE',
		'deepl'    => 'DE',
	),
	'de_DE_formal' => array(
		'code'     => 'de',
		'locale'   => 'de_DE_formal',
		'name'     => 'Deutsch',
		'label'    => 'German',
		'dir'      => 'ltr',
		'flag'     => 'de',
		'w3c'      => 'de-DE',
		'facebook' => 'de_DE',
		'deepl'    => 'DE',
	),
	'dsb' => array(
		'code'     => 'dsb',
		'locale'   => 'dsb',
		'name'     => 'Dolnoserbšćina',
		'label'    => 'Lower Sorbian',
		'dir'      => 'ltr',
		'flag'     => 'de',
	),
	'dzo' => array(
		'code'     => 'dz',
		'locale'   => 'dzo',
		'name'     => 'རྫོང་ཁ',
		'label'    => 'Dzongkha',
		'dir'      => 'ltr',
		'flag'     => 'bt',
		'w3c'      => 'dz',
	),
	'el' => array(
		'code'     => 'el',
		'locale'   => 'el',
		'name'     => 'Ελληνικά',
		'label'    => 'Greek',
		'dir'      => 'ltr',
		'flag'     => 'gr',
		'facebook' => 'el_GR',
		'deepl'    => 'EL',
	),
	'en_AU' => array(
		'code'     => 'en',
		'locale'   => 'en_AU',
		'name'     => 'English',
		'label'    => 'English',
		'dir'      => 'ltr',
		'flag'     => 'au',
		'facebook' => 'en_US',
		'deepl'    => 'EN-US',
	),
	'en_CA' => array(
		'code'     => 'en',
		'locale'   => 'en_CA',
		'name'     => 'English',
		'label'    => 'English',
		'dir'      => 'ltr',
		'flag'     => 'ca',
		'facebook' => 'en_US',
		'deepl'    => 'EN-US',
	),
	'en_GB' => array(
		'code'     => 'en',
		'locale'   => 'en_GB',
		'name'     => 'English',
		'label'    => 'English',
		'dir'      => 'ltr',
		'flag'     => 'gb',
		'facebook' => 'en_GB',
		'deepl'    => 'EN-GB',
	),
	'en_NZ' => array(
		'code'     => 'en',
		'locale'   => 'en_NZ',
		'name'     => 'English',
		'label'    => 'English',
		'dir'      => 'ltr',
		'flag'     => 'nz',
		'facebook' => 'en_US',
		'deepl'    => 'EN-US',
	),
	'en_US' => array(
		'code'     => 'en',
		'locale'   => 'en_US',
		'name'     => 'English',
		'label'    => 'English',
		'dir'      => 'ltr',
		'flag'     => 'us',
		'facebook' => 'en_US',
		'deepl'    => 'EN-US',
	),
	'en_ZA' => array(
		'code'     => 'en',
		'locale'   => 'en_ZA',
		'name'     => 'English',
		'label'    => 'English',
		'dir'      => 'ltr',
		'flag'     => 'za',
		'facebook' => 'en_US',
		'deepl'    => 'EN-US',
	),
	'eo' => array(
		'code'     => 'eo',
		'locale'   => 'eo',
		'name'     => 'Esperanto',
		'label'    => 'Esperanto',
		'dir'      => 'ltr',
		'flag'     => 'esperanto',
		'facebook' => 'eo_EO',
	),
	'es_AR' => array(
		'code'     => 'es',
		'locale'   => 'es_AR',
		'name'     => 'Español',
		'label'    => 'Spanish',
		'dir'      => 'ltr',
		'flag'     => 'ar',
		'facebook' => 'es_LA',
		'deepl'    => 'ES',
	),
	'es_CL' => array(
		'code'     => 'es',
		'locale'   => 'es_CL',
		'name'     => 'Español',
		'label'    => 'Spanish',
		'dir'      => 'ltr',
		'flag'     => 'cl',
		'facebook' => 'es_CL',
		'deepl'    => 'ES',
	),
	'es_CO' => array(
		'code'     => 'es',
		'locale'   => 'es_CO',
		'name'     => 'Español',
		'label'    => 'Spanish',
		'dir'      => 'ltr',
		'flag'     => 'co',
		'facebook' => 'es_CO',
		'deepl'    => 'ES',
	),
	'es_CR' => array(
		'code'     => 'es',
		'locale'   => 'es_CR',
		'name'     => 'Español',
		'label'    => 'Spanish',
		'dir'      => 'ltr',
		'flag'     => 'cr',
		'facebook' => 'es_LA',
		'deepl'    => 'ES',
	),
	'es_DO' => array(
		'code'     => 'es',
		'locale'   => 'es_DO',
		'name'     => 'Español',
		'label'    => 'Spanish',
		'dir'      => 'ltr',
		'flag'     => 'do',
		'facebook' => 'es_LA',
		'deepl'    => 'ES',
	),
	'es_EC' => array(
		'code'     => 'es',
		'locale'   => 'es_EC',
		'name'     => 'Español',
		'label'    => 'Spanish',
		'dir'      => 'ltr',
		'flag'     => 'ec',
		'facebook' => 'es_LA',
		'deepl'    => 'ES',
	),
	'es_ES' => array(
		'code'     => 'es',
		'locale'   => 'es_ES',
		'name'     => 'Español',
		'label'    => 'Spanish',
		'dir'      => 'ltr',
		'flag'     => 'es',
		'facebook' => 'es_ES',
		'deepl'    => 'ES',
	),
	'es_GT' => array(
		'code'     => 'es',
		'locale'   => 'es_GT',
		'name'     => 'Español',
		'label'    => 'Spanish',
		'dir'      => 'ltr',
		'flag'     => 'gt',
		'facebook' => 'es_LA',
		'deepl'    => 'ES',
	),
	'es_MX' => array(
		'code'     => 'es',
		'locale'   => 'es_MX',
		'name'     => 'Español',
		'label'    => 'Spanish',
		'dir'      => 'ltr',
		'flag'     => 'mx',
		'facebook' => 'es_MX',
		'deepl'    => 'ES',
	),
	'es_PE' => array(
		'code'     => 'es',
		'locale'   => 'es_PE',
		'name'     => 'Español',
		'label'    => 'Spanish',
		'dir'      => 'ltr',
		'flag'     => 'pe',
		'facebook' => 'es_LA',
		'deepl'    => 'ES',
	),
	'es_PR' => array(
		'code'     => 'es',
		'locale'   => 'es_PR',
		'name'     => 'Español',
		'label'    => 'Spanish',
		'dir'      => 'ltr',
		'flag'     => 'pr',
		'facebook' => 'es_LA',
		'deepl'    => 'ES',
	),
	'es_UY' => array(
		'code'     => 'es',
		'locale'   => 'es_UY',
		'name'     => 'Español',
		'label'    => 'Spanish',
		'dir'      => 'ltr',
		'flag'     => 'uy',
		'facebook' => 'es_LA',
		'deepl'    => 'ES',
	),
	'es_VE' => array(
		'code'     => 'es',
		'locale'   => 'es_VE',
		'name'     => 'Español',
		'label'    => 'Spanish',
		'dir'      => 'ltr',
		'flag'     => 've',
		'facebook' => 'es_VE',
		'deepl'    => 'ES',
	),
	'et' => array(
		'code'     => 'et',
		'locale'   => 'et',
		'name'     => 'Eesti',
		'label'    => 'Estonian',
		'dir'      => 'ltr',
		'flag'     => 'ee',
		'facebook' => 'et_EE',
		'deepl'    => 'ET',
	),
	'eu' => array(
		'code'     => 'eu',
		'locale'   => 'eu',
		'name'     => 'Euskara',
		'label'    => 'Basque',
		'dir'      => 'ltr',
		'flag'     => 'basque',
		'facebook' => 'eu_ES',
	),
	'fa_AF' => array(
		'code'     => 'fa',
		'locale'   => 'fa_AF',
		'name'     => 'فارسی',
		'label'    => 'Persian',
		'dir'      => 'rtl',
		'flag'     => 'af',
		'facebook' => 'fa_IR',
	),
	'fa_IR' => array(
		'code'     => 'fa',
		'locale'   => 'fa_IR',
		'name'     => 'فارسی',
		'label'    => 'Persian',
		'dir'      => 'rtl',
		'flag'     => 'ir',
		'facebook' => 'fa_IR',
	),
	'fi' => array(
		'code'     => 'fi',
		'locale'   => 'fi',
		'name'     => 'Suomi',
		'label'    => 'Finnish',
		'dir'      => 'ltr',
		'flag'     => 'fi',
		'facebook' => 'fi_FI',
		'deepl'    => 'FI',
	),
	'fo' => array(
		'code'     => 'fo',
		'locale'   => 'fo',
		'name'     => 'Føroyskt',
		'label'    => 'Faroese',
		'dir'      => 'ltr',
		'flag'     => 'fo',
		'facebook' => 'fo_FO',
	),
	'fr_BE' => array(
		'code'     => 'fr',
		'locale'   => 'fr_BE',
		'name'     => 'Français',
		'label'    => 'French',
		'dir'      => 'ltr',
		'flag'     => 'be',
		'facebook' => 'fr_FR',
		'deepl'    => 'FR',
	),
	'fr_CA' => array(
		'code'     => 'fr',
		'locale'   => 'fr_CA',
		'name'     => 'Français',
		'label'    => 'French',
		'dir'      => 'ltr',
		'flag'     => 'quebec',
		'facebook' => 'fr_CA',
		'deepl'    => 'FR',
	),
	'fr_FR' => array(
		'code'     => 'fr',
		'locale'   => 'fr_FR',
		'name'     => 'Français',
		'label'    => 'French',
		'dir'      => 'ltr',
		'flag'     => 'fr',
		'facebook' => 'fr_FR',
		'deepl'    => 'FR',
	),
	'fuc' => array(
		'facebook' => 'ff_NG',
		'label'    => 'Fulah',
	),
	'fur' => array(
		'code'     => 'fur',
		'locale'   => 'fur',
		'name'     => 'Furlan',
		'label'    => 'Friulian',
		'dir'      => 'ltr',
		'flag'     => 'it',
	),
	'fy' => array(
		'code'     => 'fy',
		'locale'   => 'fy',
		'name'     => 'Frysk',
		'label'    => 'Frisian',
		'dir'      => 'ltr',
		'flag'     => 'nl',
		'facebook' => 'fy_NL',
	),
	'ga' => array(
		'facebook' => 'ga_IE',
		'label'    => 'Irish',
	),
	'gax' => array(
		'facebook' => 'om_ET',
		'label'    => 'Oromo',
	),
	'gd' => array(
		'code'     => 'gd',
		'locale'   => 'gd',
		'name'     => 'Gàidhlig',
		'label'    => 'Scottish Gaelic',
		'dir'      => 'ltr',
		'flag'     => 'scotland',
	),
	'gl_ES' => array(
		'code'     => 'gl',
		'locale'   => 'gl_ES',
		'name'     => 'Galego',
		'label'    => 'Galician',
		'dir'      => 'ltr',
		'flag'     => 'galicia',
		'facebook' => 'gl_ES',
	),
	'gn' => array(
		'facebook' => 'gn_PY',
		'label'    => 'Guarani',
	),
	'gu' => array(
		'code'     => 'gu',
		'locale'   => 'gu',
		'name'     => 'ગુજરાતી',
		'label'    => 'Gujarati',
		'dir'      => 'ltr',
		'flag'     => 'in',
		'facebook' => 'gu_IN',
	),
	'hat' => array(
		'facebook' => 'ht_HT',
		'label'    => 'Haitian Creole',
	),
	'hau' => array(
		'facebook' => 'ha_NG',
		'label'    => 'Hausa',
	),
	'haz' => array(
		'code'     => 'haz',
		'locale'   => 'haz',
		'name'     => 'هزاره گی',
		'label'    => 'Hazaragi',
		'dir'      => 'rtl',
		'flag'     => 'af',
	),
	'he_IL' => array(
		'code'     => 'he',
		'locale'   => 'he_IL',
		'name'     => 'עברית',
		'label'    => 'Hebrew',
		'dir'      => 'rtl',
		'flag'     => 'il',
		'facebook' => 'he_IL',
	),
	'hi_IN' => array(
		'code'     => 'hi',
		'locale'   => 'hi_IN',
		'name'     => 'हिन्दी',
		'label'    => 'Hindi',
		'dir'      => 'ltr',
		'flag'     => 'in',
		'facebook' => 'hi_IN',
	),
	'hr' => array(
		'code'     => 'hr',
		'locale'   => 'hr',
		'name'     => 'Hrvatski',
		'label'    => 'Croatian',
		'dir'      => 'ltr',
		'flag'     => 'hr',
		'facebook' => 'hr_HR',
	),
	'hu_HU' => array(
		'code'     => 'hu',
		'locale'   => 'hu_HU',
		'name'     => 'Magyar',
		'label'    => 'Hungarian',
		'dir'      => 'ltr',
		'flag'     => 'hu',
		'facebook' => 'hu_HU',
		'deepl'    => 'HU',
	),
	'hsb' => array(
		'code'     => 'hsb',
		'locale'   => 'hsb',
		'name'     => 'Hornjoserbšćina',
		'label'    => 'Upper Sorbian',
		'dir'      => 'ltr',
		'flag'     => 'de',
	),
	'hy' => array(
		'code'     => 'hy',
		'locale'   => 'hy',
		'name'     => 'Հայերեն',
		'label'    => 'Armenian',
		'dir'      => 'ltr',
		'flag'     => 'am',
		'facebook' => 'hy_AM',
	),
	'id_ID' => array(
		'code'     => 'id',
		'locale'   => 'id_ID',
		'name'     => 'Bahasa Indonesia',
		'label'    => 'Indonesian',
		'dir'      => 'ltr',
		'flag'     => 'id',
		'facebook' => 'id_ID',
		'deepl'    => 'ID',
	),
	'ido' => array(
		'w3c'      => 'io',
		'label'    => 'Ido',
	),
	'is_IS' => array(
		'code'     => 'is',
		'locale'   => 'is_IS',
		'name'     => 'Íslenska',
		'label'    => 'Icelandic',
		'dir'      => 'ltr',
		'flag'     => 'is',
		'facebook' => 'is_IS',
	),
	'it_IT' => array(
		'code'     => 'it',
		'locale'   => 'it_IT',
		'name'     => 'Italiano',
		'label'    => 'Italian',
		'dir'      => 'ltr',
		'flag'     => 'it',
		'facebook' => 'it_IT',
		'deepl'    => 'IT',
	),
	'ja' => array(
		'code'     => 'ja',
		'locale'   => 'ja',
		'name'     => '日本語',
		'label'    => 'Japanese',
		'dir'      => 'ltr',
		'flag'     => 'jp',
		'facebook' => 'ja_JP',
		'deepl'    => 'JA',
	),
	'jv_ID' => array(
		'code'     => 'jv',
		'locale'   => 'jv_ID',
		'name'     => 'Basa Jawa',
		'label'    => 'Javanese',
		'dir'      => 'ltr',
		'flag'     => 'id',
		'facebook' => 'jv_ID',
	),
	'ka_GE' => array(
		'code'     => 'ka',
		'locale'   => 'ka_GE',
		'name'     => 'ქართული',
		'label'    => 'Georgian',
		'dir'      => 'ltr',
		'flag'     => 'ge',
		'facebook' => 'ka_GE',
	),
	'kab' => array(
		'code'     => 'kab',
		'locale'   => 'kab',
		'name'     => 'Taqbaylit',
		'label'    => 'Kabyle',
		'dir'      => 'ltr',
		'flag'     => 'dz',
	),
	'kin' => array(
		'w3c'      => 'rw',
		'facebook' => 'rw_RW',
		'label'    => 'Kinyarwanda',
	),
	'kir' => array(
		'code'     => 'ky',
		'locale'   => 'kir',
		'name'     => 'Кыргызча',
		'label'    => 'Kyrgyz',
		'dir'      => 'ltr',
		'flag'     => 'kg',
	),
	'kk' => array(
		'code'     => 'kk',
		'locale'   => 'kk',
		'name'     => 'Қазақ тілі',
		'label'    => 'Kazakh',
		'dir'      => 'ltr',
		'flag'     => 'kz',
		'facebook' => 'kk_KZ',
	),
	'km' => array(
		'code'     => 'km',
		'locale'   => 'km',
		'name'     => 'ភាសាខ្មែរ',
		'label'    => 'Khmer',
		'dir'      => 'ltr',
		'flag'     => 'kh',
		'facebook' => 'km_KH',
	),
	'kn' => array(
		'code'     => 'kn',
		'locale'   => 'kn',
		'name'     => 'ಕನ್ನಡ',
		'label'    => 'Kannada',
		'dir'      => 'ltr',
		'flag'     => 'in',
		'facebook' => 'kn_IN',
	),
	'ko_KR' => array(
		'code'     => 'ko',
		'locale'   => 'ko_KR',
		'name'     => '한국어',
		'label'    => 'Korean',
		'dir'      => 'ltr',
		'flag'     => 'kr',
		'facebook' => 'ko_KR',
		'deepl'    => 'KO',
	),
	'ku' => array(
		'facebook' => 'ku_TR',
		'label'    => 'Kurdish (Kurmanji)',
	),
	'ky_KY' => array(
		'facebook' => 'ky_KG',
		'label'    => 'Kyrgyz',
	),
	'la' => array(
		'facebook' => 'la_VA',
		'label'    => 'Latin',
	),
	'li' => array(
		'facebook' => 'li_NL',
		'label'    => 'Limburgish',
	),
	'lin' => array(
		'facebook' => 'ln_CD',
		'label'    => 'Lingala',
	),
	'lo' => array(
		'code'     => 'lo',
		'locale'   => 'lo',
		'name'     => 'ພາສາລາວ',
		'label'    => 'Lao',
		'dir'      => 'ltr',
		'flag'     => 'la',
		'facebook' => 'lo_LA',
	),
	'lt_LT' => array(
		'code'     => 'lt',
		'locale'   => 'lt_LT',
		'name'     => 'Lietuviškai',
		'label'    => 'Lithuanian',
		'dir'      => 'ltr',
		'flag'     => 'lt',
		'facebook' => 'lt_LT',
		'deepl'    => 'LT',
	),
	'lv' => array(
		'code'     => 'lv',
		'locale'   => 'lv',
		'name'     => 'Latviešu valoda',
		'label'    => 'Latvian',
		'dir'      => 'ltr',
		'flag'     => 'lv',
		'facebook' => 'lv_LV',
		'deepl'    => 'LV',
	),
	'mg_MG' => array(
		'facebook' => 'mg_MG',
		'label'    => 'Malagasy',
	),
	'mk_MK' => array(
		'code'     => 'mk',
		'locale'   => 'mk_MK',
		'name'     => 'македонски јазик',
		'label'    => 'Macedonian',
		'dir'      => 'ltr',
		'flag'     => 'mk',
		'facebook' => 'mk_MK',
	),
	'ml_IN' => array(
		'code'     => 'ml',
		'locale'   => 'ml_IN',
		'name'     => 'മലയാളം',
		'label'    => 'Malayalam',
		'dir'      => 'ltr',
		'flag'     => 'in',
		'facebook' => 'ml_IN',
	),
	'mlt' => array(
		'facebook' => 'mt_MT',
		'label'    => 'Maltese',
	),
	'mn' => array(
		'code'     => 'mn',
		'locale'   => 'mn',
		'name'     => 'Монгол хэл',
		'label'    => 'Mongolian',
		'dir'      => 'ltr',
		'flag'     => 'mn',
		'facebook' => 'mn_MN',
	),
	'mr' => array(
		'code'     => 'mr',
		'locale'   => 'mr',
		'name'     => 'मराठी',
		'label'    => 'Marathi',
		'dir'      => 'ltr',
		'flag'     => 'in',
		'facebook' => 'mr_IN',
	),
	'mri' => array(
		'w3c'      => 'mi',
		'facebook' => 'mi_NZ',
		'label'    => 'Maori',
	),
	'ms_MY' => array(
		'code'     => 'ms',
		'locale'   => 'ms_MY',
		'name'     => 'Bahasa Melayu',
		'label'    => 'Malay',
		'dir'      => 'ltr',
		'flag'     => 'my',
		'facebook' => 'ms_MY',
	),
	'my_MM' => array(
		'code'     => 'my',
		'locale'   => 'my_MM',
		'name'     => 'ဗမာစာ',
		'label'    => 'Burmese',
		'dir'      => 'ltr',
		'flag'     => 'mm',
		'facebook' => 'my_MM',
	),
	'nb_NO' => array(
		'code'     => 'nb',
		'locale'   => 'nb_NO',
		'name'     => 'Norsk Bokmål',
		'label'    => 'Norwegian Bokmål',
		'dir'      => 'ltr',
		'flag'     => 'no',
		'facebook' => 'nb_NO',
		'deepl'    => 'NB',
	),
	'ne_NP' => array(
		'code'     => 'ne',
		'locale'   => 'ne_NP',
		'name'     => 'नेपाली',
		'label'    => 'Nepali',
		'dir'      => 'ltr',
		'flag'     => 'np',
		'facebook' => 'ne_NP',
	),
	'nl_BE' => array(
		'code'     => 'nl',
		'locale'   => 'nl_BE',
		'name'     => 'Nederlands',
		'label'    => 'Dutch',
		'dir'      => 'ltr',
		'flag'     => 'be',
		'facebook' => 'nl_BE',
		'deepl'    => 'NL',
	),
	'nl_NL' => array(
		'code'     => 'nl',
		'locale'   => 'nl_NL',
		'name'     => 'Nederlands',
		'label'    => 'Dutch',
		'dir'      => 'ltr',
		'flag'     => 'nl',
		'facebook' => 'nl_NL',
		'deepl'    => 'NL',
	),
	'nl_NL_formal' => array(
		'code'     => 'nl',
		'locale'   => 'nl_NL_formal',
		'name'     => 'Nederlands',
		'label'    => 'Dutch',
		'dir'      => 'ltr',
		'flag'     => 'nl',
		'w3c'      => 'nl-NL',
		'facebook' => 'nl_NL',
		'deepl'    => 'NL',
	),
	'nn_NO' => array(
		'code'     => 'nn',
		'locale'   => 'nn_NO',
		'name'     => 'Norsk Nynorsk',
		'label'    => 'Norwegian Nynorsk',
		'dir'      => 'ltr',
		'flag'     => 'no',
		'facebook' => 'nn_NO',
	),
	'oci' => array(
		'code'     => 'oc',
		'locale'   => 'oci',
		'name'     => 'Occitan',
		'label'    => 'Occitan',
		'dir'      => 'ltr',
		'flag'     => 'occitania',
		'w3c'      => 'oc',
	),
	'ory' => array(
		'facebook' => 'or_IN',
		'label'    => 'Oriya',
	),
	'pa_IN' => array(
		'code'     => 'pa',
		'locale'   => 'pa_IN',
		'name'     => 'ਪੰਜਾਬੀ',
		'label'    => 'Punjabi',
		'dir'      => 'ltr',
		'flag'     => 'in',
		'facebook' => 'pa_IN',
	),
	'pl_PL' => array(
		'code'     => 'pl',
		'locale'   => 'pl_PL',
		'name'     => 'Polski',
		'label'    => 'Polish',
		'dir'      => 'ltr',
		'flag'     => 'pl',
		'facebook' => 'pl_PL',
		'deepl'    => 'PL',
	),
	'ps' => array(
		'code'     => 'ps',
		'locale'   => 'ps',
		'name'     => 'پښتو',
		'label'    => 'Pashto',
		'dir'      => 'rtl',
		'flag'     => 'af',
		'facebook' => 'ps_AF',
	),
	'pt_AO' => array(
		'code'     => 'pt',
		'locale'   => 'pt_AO',
		'name'     => 'Português',
		'label'    => 'Portuguese',
		'dir'      => 'ltr',
		'flag'     => 'ao',
		'facebook' => 'pt_PT',
		'deepl'    => 'PT-PT',
	),
	'pt_BR' => array(
		'code'     => 'pt',
		'locale'   => 'pt_BR',
		'name'     => 'Português',
		'label'    => 'Portuguese',
		'dir'      => 'ltr',
		'flag'     => 'br',
		'facebook' => 'pt_BR',
		'deepl'    => 'PT-BR',
	),
	'pt_PT' => array(
		'code'     => 'pt',
		'locale'   => 'pt_PT',
		'name'     => 'Português',
		'label'    => 'Portuguese',
		'dir'      => 'ltr',
		'flag'     => 'pt',
		'facebook' => 'pt_PT',
		'deepl'    => 'PT-PT',
	),
	'pt_PT_ao90' => array(
		'code'     => 'pt',
		'locale'   => 'pt_PT_ao90',
		'name'     => 'Português',
		'label'    => 'Portuguese',
		'dir'      => 'ltr',
		'flag'     => 'pt',
		'facebook' => 'pt_PT',
		'deepl'    => 'PT-PT',
	),
	'rhg' => array(
		'code'     => 'rhg',
		'locale'   => 'rhg',
		'name'     => 'Ruáinga',
		'label'    => 'Rohingya',
		'dir'      => 'ltr',
		'flag'     => 'mm',
	),
	'ro_RO' => array(
		'code'     => 'ro',
		'locale'   => 'ro_RO',
		'name'     => 'Română',
		'label'    => 'Romanian',
		'dir'      => 'ltr',
		'flag'     => 'ro',
		'facebook' => 'ro_RO',
		'deepl'    => 'RO',
	),
	'roh' => array(
		'w3c'      => 'rm',
		'facebook' => 'rm_CH',
		'label'    => 'Romansh',
	),
	'ru_RU' => array(
		'code'     => 'ru',
		'locale'   => 'ru_RU',
		'name'     => 'Русский',
		'label'    => 'Russian',
		'dir'      => 'ltr',
		'flag'     => 'ru',
		'facebook' => 'ru_RU',
		'deepl'    => 'RU',
	),
	'sa_IN' => array(
		'facebook' => 'sa_IN',
		'label'    => 'Sanskrit',
	),
	'sah' => array(
		'code'     => 'sah',
		'locale'   => 'sah',
		'name'     => 'Сахалыы',
		'label'    => 'Sakha',
		'dir'      => 'ltr',
		'flag'     => 'ru',
	),
	'si_LK' => array(
		'code'     => 'si',
		'locale'   => 'si_LK',
		'name'     => 'සිංහල',
		'label'    => 'Sinhala',
		'dir'      => 'ltr',
		'flag'     => 'lk',
		'facebook' => 'si_LK',
	),
	'sk_SK' => array(
		'code'     => 'sk',
		'locale'   => 'sk_SK',
		'name'     => 'Slovenčina',
		'label'    => 'Slovak',
		'dir'      => 'ltr',
		'flag'     => 'sk',
		'facebook' => 'sk_SK',
		'deepl'    => 'SK',
	),
	'skr' => array(
		'code'     => 'skr',
		'locale'   => 'skr',
		'name'     => 'سرائیکی',
		'label'    => 'Saraiki',
		'dir'      => 'rtl',
		'flag'     => 'pk',
	),
	'sl_SI' => array(
		'code'     => 'sl',
		'locale'   => 'sl_SI',
		'name'     => 'Slovenščina',
		'label'    => 'Slovenian',
		'dir'      => 'ltr',
		'flag'     => 'si',
		'facebook' => 'sl_SI',
		'deepl'    => 'SL',
	),
	'sna' => array(
		'facebook' => 'sn_ZW',
		'label'    => 'Shona',
	),
	'snd' => array(
		'code'     => 'sd',
		'locale'   => 'snd',
		'name'     => 'سنڌي',
		'label'    => 'Sindhi',
		'dir'      => 'rtl',
		'flag'     => 'pk',
	),
	'so_SO' => array(
		'code'     => 'so',
		'locale'   => 'so_SO',
		'name'     => 'Af-Soomaali',
		'label'    => 'Somali',
		'dir'      => 'ltr',
		'flag'     => 'so',
		'facebook' => 'so_SO',
	),
	'sq' => array(
		'code'     => 'sq',
		'locale'   => 'sq',
		'name'     => 'Shqip',
		'label'    => 'Albanian',
		'dir'      => 'ltr',
		'flag'     => 'al',
		'facebook' => 'sq_AL',
	),
	'sr_RS' => array(
		'code'     => 'sr',
		'locale'   => 'sr_RS',
		'name'     => 'Српски језик',
		'label'    => 'Serbian',
		'dir'      => 'ltr',
		'flag'     => 'rs',
		'facebook' => 'sr_RS',
	),
	'srd' => array(
		'w3c'      => 'sc',
		'facebook' => 'sc_IT',
		'label'    => 'Sardinian',
	),
	'su_ID' => array(
		'code'     => 'su',
		'locale'   => 'su_ID',
		'name'     => 'Basa Sunda',
		'label'    => 'Sundanese',
		'dir'      => 'ltr',
		'flag'     => 'id',
		'facebook' => 'su_ID',
	),
	'sv_SE' => array(
		'code'     => 'sv',
		'locale'   => 'sv_SE',
		'name'     => 'Svenska',
		'label'    => 'Swedish',
		'dir'      => 'ltr',
		'flag'     => 'se',
		'facebook' => 'sv_SE',
		'deepl'    => 'SV',
	),
	'sw' => array(
		'code'     => 'sw',
		'locale'   => 'sw',
		'name'     => 'Kiswahili',
		'label'    => 'Swahili',
		'dir'      => 'ltr',
		'flag'     => 'ke',
		'facebook' => 'sw_KE',
	),
	'syr' => array(
		'facebook' => 'sy_SY',
		'label'    => 'Syriac',
	),
	'szl' => array(
		'code'     => 'szl',
		'locale'   => 'szl',
		'name'     => 'Ślōnskŏ gŏdka',
		'label'    => 'Silesian',
		'dir'      => 'ltr',
		'flag'     => 'pl',
		'facebook' => 'sz_PL',
	),
	'ta_IN' => array(
		'code'     => 'ta',
		'locale'   => 'ta_IN',
		'name'     => 'தமிழ்',
		'label'    => 'Tamil',
		'dir'      => 'ltr',
		'flag'     => 'in',
		'facebook' => 'ta_IN',
	),
	'ta_LK' => array(
		'code'     => 'ta',
		'locale'   => 'ta_LK',
		'name'     => 'தமிழ்',
		'label'    => 'Tamil',
		'dir'      => 'ltr',
		'flag'     => 'lk',
		'facebook' => 'ta_IN',
	),
	'tah' => array(
		'code'     => 'ty',
		'locale'   => 'tah',
		'name'     => 'Reo Tahiti',
		'label'    => 'Tahitian',
		'dir'      => 'ltr',
		'flag'     => 'pf',
	),
	'te' => array(
		'code'     => 'te',
		'locale'   => 'te',
		'name'     => 'తెలుగు',
		'label'    => 'Telugu',
		'dir'      => 'ltr',
		'flag'     => 'in',
		'facebook' => 'te_IN',
	),
	'tg' => array(
		'facebook' => 'tg_TJ',
		'label'    => 'Tajik',
	),
	'th' => array(
		'code'     => 'th',
		'locale'   => 'th',
		'name'     => 'ไทย',
		'label'    => 'Thai',
		'dir'      => 'ltr',
		'flag'     => 'th',
		'facebook' => 'th_TH',
	),
	'tl' => array(
		'code'     => 'tl',
		'locale'   => 'tl',
		'name'     => 'Tagalog',
		'label'    => 'Tagalog',
		'dir'      => 'ltr',
		'flag'     => 'ph',
		'facebook' => 'tl_PH',
	),
	'tr_TR' => array(
		'code'     => 'tr',
		'locale'   => 'tr_TR',
		'name'     => 'Türkçe',
		'label'    => 'Turkish',
		'dir'      => 'ltr',
		'flag'     => 'tr',
		'facebook' => 'tr_TR',
		'deepl'    => 'TR',
	),
	'tt_RU' => array(
		'code'     => 'tt',
		'locale'   => 'tt_RU',
		'name'     => 'Татар теле',
		'label'    => 'Tatar',
		'dir'      => 'ltr',
		'flag'     => 'ru',
		'facebook' => 'tt_RU',
	),
	'tuk' => array(
		'w3c'      => 'tk',
		'facebook' => 'tk_TM',
		'label'    => 'Turkmen',
	),
	'tzm' => array(
		'facebook' => 'tz_MA',
		'label'    => 'Tamazight',
	),
	'ug_CN' => array(
		'code'     => 'ug',
		'locale'   => 'ug_CN',
		'name'     => 'Uyƣurqə',
		'label'    => 'Uyghur',
		'dir'      => 'ltr',
		'flag'     => 'cn',
	),
	'uk' => array(
		'code'     => 'uk',
		'locale'   => 'uk',
		'name'     => 'Українська',
		'label'    => 'Ukrainian',
		'dir'      => 'ltr',
		'flag'     => 'ua',
		'facebook' => 'uk_UA',
		'deepl'    => 'UK',
	),
	'ur' => array(
		'code'     => 'ur',
		'locale'   => 'ur',
		'name'     => 'اردو',
		'label'    => 'Urdu',
		'dir'      => 'rtl',
		'flag'     => 'pk',
		'facebook' => 'ur_PK',
	),
	'uz_UZ' => array(
		'code'     => 'uz',
		'locale'   => 'uz_UZ',
		'name'     => 'Oʻzbek',
		'label'    => 'Uzbek',
		'dir'      => 'ltr',
		'flag'     => 'uz',
		'facebook' => 'uz_UZ',
	),
	'vec' => array(
		'code'     => 'vec',
		'locale'   => 'vec',
		'name'     => 'Vèneto',
		'label'    => 'Venetian',
		'dir'      => 'ltr',
		'flag'     => 'veneto',
	),
	'vi' => array(
		'code'     => 'vi',
		'locale'   => 'vi',
		'name'     => 'Tiếng Việt',
		'label'    => 'Vietnamese',
		'dir'      => 'ltr',
		'flag'     => 'vn',
		'facebook' => 'VI',
	),
	'xho' => array(
		'facebook' => 'xh_ZA',
		'label'    => 'Xhosa',
	),
	'yor' => array(
		'facebook' => 'yo_NG',
		'label'    => 'Yoruba',
	),
	'zh_CN' => array(
		'code'     => 'zh',
		'locale'   => 'zh_CN',
		'name'     => '中文 (中国)',
		'label'    => 'Simplified Chinese (Mandarin)',
		'dir'      => 'ltr',
		'flag'     => 'cn',
		'facebook' => 'zh_CN',
		'deepl'    => 'ZH-HANS',
	),
	'zh_HK' => array(
		'code'     => 'zh',
		'locale'   => 'zh_HK',
		'name'     => '中文 (香港)',
		'label'    => 'Traditional Chinese (Hong Kong)',
		'dir'      => 'ltr',
		'flag'     => 'hk',
		'facebook' => 'zh_HK',
		'deepl'    => 'ZH-HANT',
	),
	'zh_TW' => array(
		'code'     => 'zh',
		'locale'   => 'zh_TW',
		'name'     => '中文 (台灣)',
		'label'    => 'Simplified Chinese (Mandarin)',
		'dir'      => 'ltr',
		'flag'     => 'tw',
		'facebook' => 'zh_TW',
		'deepl'    => 'ZH-HANT',
	),
);